[tool.poetry]
name = "securereverseshell"
version = "0.1.0"
description = ""
authors = ["Jim Coyne <jicoyne@cisco.com>"]

[tool.poetry.dependencies]
python = "^3.8"
paramiko = "^2.7.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
